package ir.bank.qh.party.enums;

/** {@code REF_LEGAL_FORM} on ORGANIZATION. */
public enum LegalForm {
    SOLE_PROPRIETORSHIP,
    LIMITED_LIABILITY_COMPANY,
    JOINT_STOCK_COMPANY,
    PARTNERSHIP,
    COOPERATIVE,
    GOVERNMENT_ENTITY,
    NONPROFIT_ENTITY,
    BRANCH_OF_FOREIGN_COMPANY
}
