-- ============================================================
-- Party module seed data (schema PARTY)
-- Educational/demo data only - not real customer information.
-- Institution (tenant) 1 = the single demo bank used throughout this project.
-- ============================================================

-- ---------- Shared reference/master data (BaseEntity, no tenant column) ----------
INSERT INTO PARTY.COUNTRY (COUNTRY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, NAME, ISO_CODE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'Iran', 'IRN');
INSERT INTO PARTY.COUNTRY (COUNTRY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, NAME, ISO_CODE)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'United Arab Emirates', 'ARE');

INSERT INTO PARTY.CITY (CITY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, COUNTRY_ID, PROVINCE_NAME, NAME)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'تهران', 'تهران');
INSERT INTO PARTY.CITY (CITY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, COUNTRY_ID, PROVINCE_NAME, NAME)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'اصفهان', 'اصفهان');
INSERT INTO PARTY.CITY (CITY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, COUNTRY_ID, PROVINCE_NAME, NAME)
VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 2, 'Dubai', 'Dubai');

-- ---------- ADDRESS (tenant-scoped, plain country/city/county codes - no FK to COUNTRY/CITY) ----------
INSERT INTO PARTY.ADDRESS (ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    COUNTRY_CODE, PROVINCE_CODE, CITY_CODE, MAIN_STREET_TEXT, PLAQUE_NO, UNIT_NO, POSTAL_CODE, ADDRESS_LINE_1)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'IRN', 'THR', 'TEHRAN', 'خیابان ولیعصر', '125', '4', '1234567890',
    'تهران، خیابان ولیعصر، پلاک ۱۲۵، واحد ۴');
INSERT INTO PARTY.ADDRESS (ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    COUNTRY_CODE, PROVINCE_CODE, CITY_CODE, MAIN_STREET_TEXT, PLAQUE_NO, POSTAL_CODE, ADDRESS_LINE_1)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'IRN', 'THR', 'TEHRAN', 'بلوار میرداماد', '48', '1987654321',
    'تهران، بلوار میرداماد، پلاک ۴۸ (دفتر مرکزی شرکت)');

-- ---------- PARTY root (JOINED inheritance: PARTY_TYPE_CODE is the discriminator) ----------
INSERT INTO PARTY.PARTY (PARTY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_TYPE_CODE, VERIFICATION_STATUS_CODE, CREATION_SOURCE_CODE, IS_CURRENT)
VALUES (1001, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'PERSON', 'VERIFIED', 'BRANCH_ENTRY', 'Y');
INSERT INTO PARTY.PARTY (PARTY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_TYPE_CODE, VERIFICATION_STATUS_CODE, CREATION_SOURCE_CODE, IS_CURRENT)
VALUES (2001, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'ORGANIZATION', 'VERIFIED', 'BRANCH_ENTRY', 'Y');

-- ---------- PERSON (subtype row, shares PARTY_ID as PK/FK) ----------
INSERT INTO PARTY.PERSON (PARTY_ID, BIRTH_DATE, GENDER_CODE, BIRTH_COUNTRY_CODE, BIRTH_PLACE_ID,
    FATHER_GIVEN_NAME, MARITAL_STATUS_CODE, RESIDENCE_STATUS_CODE, PHYSICAL_ABILITY)
VALUES (1001, DATE '1990-05-15', 'MALE', 'IRN', 1, 'علی', 'MARRIED', 'RESIDENT', 'NONE');

-- ---------- ORGANIZATION (subtype row, shares PARTY_ID as PK/FK) ----------
INSERT INTO PARTY.ORGANIZATION (PARTY_ID, REGISTERED_NAME, REGISTRATION_NO, REGISTRATION_COUNTRY_CODE,
    INCORPORATION_DATE, LISTED_COMPANY_FLAG, ACTIVITY_STATUS_CODE, MAIN_ACTIVITY_DESCRIPTION,
    EMPLOYEE_COUNT, ENTERPRISE_SIZE_CODE, OWNERSHIP_TYPE_CODE)
VALUES (2001, 'شرکت تعاونی نمونه قرض‌الحسنه', '12345', 'IRN',
    DATE '2015-01-01', 'N', 'ACTIVE', 'خدمات مالی و قرض‌الحسنه',
    25, 'SMALL', 'PRIVATE');

-- ---------- CUSTOMER (customer lifecycle/KYC status, shares PARTY_ID as PK/FK) ----------
INSERT INTO PARTY.CUSTOMER (PARTY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    CUSTOMER_NO, CUSTOMER_STATUS_CODE, ONBOARDING_DATE, KYC_STATUS_CODE, HOME_BRANCH_CODE)
VALUES (1001, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'CUST-0001001', 'ACTIVE', DATE '2020-01-01', 'VERIFIED', 'BR-001');
INSERT INTO PARTY.CUSTOMER (PARTY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    CUSTOMER_NO, CUSTOMER_STATUS_CODE, ONBOARDING_DATE, KYC_STATUS_CODE, HOME_BRANCH_CODE)
VALUES (2001, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'CUST-0002001', 'ACTIVE', DATE '2015-01-01', 'VERIFIED', 'BR-001');

-- ---------- PARTY_MEMBERSHIP ----------
INSERT INTO PARTY.PARTY_MEMBERSHIP (PARTY_MEMBERSHIP_ID, CREATED_ON, CREATED_BY, INSTITUTION_ID,
    PARTY_ID, CUSTOMER_NO)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1001, 'CUST-0001001');
INSERT INTO PARTY.PARTY_MEMBERSHIP (PARTY_MEMBERSHIP_ID, CREATED_ON, CREATED_BY, INSTITUTION_ID,
    PARTY_ID, CUSTOMER_NO)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2001, 'CUST-0002001');

-- ---------- ORGANIZATION_OFFICER (person acting as an officer of the organization) ----------
INSERT INTO PARTY.ORGANIZATION_OFFICER (ORGANIZATION_OFFICER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    INSTITUTION_ID, ORGANIZATION_PARTY_ID, OFFICER_PARTY_ID, OFFICER_ROLE_CODE, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 1001, 'MANAGING_DIRECTOR', DATE '2015-01-01');

-- ---------- PARTY_NAME ----------
INSERT INTO PARTY.PARTY_NAME (PARTY_NAME_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, GIVEN_NAME, FAMILY_NAME, FULL_NAME, IS_PRIMARY)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'محمد', 'رضایی', 'محمد رضایی', 'Y');
INSERT INTO PARTY.PARTY_NAME (PARTY_NAME_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, FULL_NAME, IS_PRIMARY)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 'شرکت تعاونی نمونه قرض‌الحسنه', 'Y');

-- ---------- PARTY_IDENTIFIER ----------
INSERT INTO PARTY.PARTY_IDENTIFIER (PARTY_IDENTIFIER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, IDENTIFIER_TYPE_CODE, IDENTIFIER_VALUE,
    ISSUE_DATE, IS_PRIMARY, IS_ACTIVE, VERIFICATION_STATUS_CODE, VERIFICATION_METHOD_CODE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'NATIONAL_ID', '0012345678',
    DATE '2008-06-01', 'Y', 'Y', 'VERIFIED', 'IN_PERSON');
INSERT INTO PARTY.PARTY_IDENTIFIER (PARTY_IDENTIFIER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, IDENTIFIER_TYPE_CODE, IDENTIFIER_VALUE,
    IS_PRIMARY, IS_ACTIVE, VERIFICATION_STATUS_CODE, VERIFICATION_METHOD_CODE)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 'REGISTRATION_NUMBER', '12345',
    'Y', 'Y', 'VERIFIED', 'DOCUMENT_REVIEW');

-- ---------- CONTACT_POINT ----------
INSERT INTO PARTY.CONTACT_POINT (CONTACT_POINT_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, CONTACT_TYPE_CODE, CONTACT_VALUE, PURPOSE_CODE, IS_PRIMARY)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'MOBILE_PHONE', '+989121234567', 'PERSONAL', 'Y');
INSERT INTO PARTY.CONTACT_POINT (CONTACT_POINT_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, CONTACT_TYPE_CODE, CONTACT_VALUE, PURPOSE_CODE, IS_PRIMARY)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'EMAIL', 'mohammad.rezaei@example.com', 'PERSONAL', 'N');
INSERT INTO PARTY.CONTACT_POINT (CONTACT_POINT_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, CONTACT_TYPE_CODE, CONTACT_VALUE, AREA_CODE, PURPOSE_CODE, IS_PRIMARY)
VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 'LANDLINE_PHONE', '88889999', '021', 'BUSINESS', 'Y');

-- ---------- PARTY_ADDRESS ----------
INSERT INTO PARTY.PARTY_ADDRESS (PARTY_ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, ADDRESS_ID, ADDRESS_TYPE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 1, 'RESIDENTIAL', 'Y', DATE '2020-01-01');
INSERT INTO PARTY.PARTY_ADDRESS (PARTY_ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, ADDRESS_ID, ADDRESS_TYPE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 2, 'REGISTERED', 'Y', DATE '2015-01-01');

-- ---------- CONTACT_POINT_ADDRESS (org landline is located at the registered office) ----------
INSERT INTO PARTY.CONTACT_POINT_ADDRESS (CONTACT_POINT_ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    INSTITUTION_ID, CONTACT_POINT_ID, PARTY_ADDRESS_ID, ASSOCIATION_TYPE_CODE, IS_PRIMARY_FOR_ADDRESS)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 3, 2, 'LOCATED_AT', 'Y');

-- ---------- PARTY_DEMOGRAPHIC (KYC profile, one-to-one with PARTY) ----------
INSERT INTO PARTY.PARTY_DEMOGRAPHIC (PARTY_DEMOGRAPHIC_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, OCCUPATION_OR_INDUSTRY, EMPLOYER_NAME, EDUCATION_LEVEL, SOURCE_OF_FUNDS, ESTIMATED_ANNUAL_INCOME)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'کارمند بانک', 'بانک قرض‌الحسنه نمونه', 'کارشناسی ارشد',
    'حقوق و دستمزد', 800000000.00);

-- ---------- PARTY_ROLE (generic role/context extensibility point) ----------
INSERT INTO PARTY.PARTY_ROLE (PARTY_ROLE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, ROLE_TYPE_CODE, CONTEXT_TYPE_CODE, CONTEXT_ID, VALID_FROM, WORKFLOW_STATUS_CODE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'CUSTOMER', 'ACCOUNT', 'ACC-0001001', DATE '2020-01-01', 'ACTIVE');
INSERT INTO PARTY.PARTY_ROLE (PARTY_ROLE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, ROLE_TYPE_CODE, CONTEXT_TYPE_CODE, CONTEXT_ID, PRINCIPAL_PARTY_ID, AUTHORITY_BASIS_CODE,
    AUTHORITY_DOCUMENT_NO, VALID_FROM, WORKFLOW_STATUS_CODE)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'LEGAL_REPRESENTATIVE', 'CONTRACT', 'CTR-0000500', 2001,
    'POWER_OF_ATTORNEY', 'POA-2026-001', DATE '2020-01-01', 'ACTIVE');
INSERT INTO PARTY.PARTY_ROLE (PARTY_ROLE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, ROLE_TYPE_CODE, CONTEXT_TYPE_CODE, CONTEXT_ID, VALID_FROM, WORKFLOW_STATUS_CODE)
VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 'CUSTOMER', 'ACCOUNT', 'ACC-0002001', DATE '2015-01-01', 'ACTIVE');

-- ---------- PARTY_GROUP + PARTY_GROUP_MEMBER (ownership / UBO tracking) ----------
INSERT INTO PARTY.PARTY_GROUP (GROUP_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    GROUP_TYPE_CODE, GROUP_NAME, STATUS_CODE, EFFECTIVE_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'OWNERSHIP', 'ساختار مالکیت شرکت تعاونی نمونه', 'ACTIVE',
    DATE '2015-01-01');
INSERT INTO PARTY.PARTY_GROUP_MEMBER (GROUP_MEMBER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    GROUP_ID, PARTY_ID, MEMBER_ROLE_CODE, OWNERSHIP_PERCENT, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 1001, 'OWNER', 100.000, DATE '2015-01-01');

-- ---------- SIGNATURE_SPECIMEN ----------
INSERT INTO PARTY.SIGNATURE_SPECIMEN (SIGNATURE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, SPECIMEN_TYPE_CODE, EFFECTIVE_FROM, STATUS_CODE, SIGNING_RULE_CODE, VERIFICATION_STATUS_CODE,
    CAPTURE_CHANNEL_CODE, CAPTURED_BY)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'WET_SIGNATURE', DATE '2020-01-01', 'ACTIVE', 'SINGLE',
    'VERIFIED', 'BRANCH_COUNTER', 'SEED');

-- ---------- PARTY_INQUIRY (compliance check audit trail) ----------
INSERT INTO PARTY.PARTY_INQUIRY (PARTY_INQUIRY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, INQUIRY_TYPE_CODE, RESULT_VALUE, STATUS_CODE, INQUIRY_DATE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 'KYC_CHECK', 1, 'COMPLETED', TIMESTAMP '2026-01-01 09:00:00');
INSERT INTO PARTY.PARTY_INQUIRY (PARTY_INQUIRY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID, INQUIRY_TYPE_CODE, RESULT_VALUE, STATUS_CODE, INQUIRY_DATE)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, 'SANCTIONS_LIST_CHECK', 0, 'COMPLETED', TIMESTAMP '2026-01-01 09:05:00');

-- ============================================================
-- Advance every sequence past the explicit seed IDs used above,
-- so subsequent inserts through the REST API never collide.
-- ============================================================
ALTER SEQUENCE PARTY.COUNTRY_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.CITY_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.ADDRESS_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_ID_SEQ RESTART WITH 3001;
ALTER SEQUENCE PARTY.PARTY_NAME_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_IDENTIFIER_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.CONTACT_POINT_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_ADDRESS_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.CONTACT_POINT_ADDRESS_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_DEMOGRAPHIC_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_ROLE_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_GROUP_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_GROUP_MEMBER_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.SIGNATURE_SPECIMEN_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_INQUIRY_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_MEMBERSHIP_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.ORGANIZATION_OFFICER_ID_SEQ RESTART WITH 100;
