-- ============================================================
-- 05 - Reference Data
-- ============================================================
INSERT INTO REFERENCE.document_type (id, created_on, created_by, record_version, document_type_code, document_type_name, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'NATIONAL_ID', 'کارت / شناسه ملی', 'ACTIVE');
INSERT INTO REFERENCE.document_type (id, created_on, created_by, record_version, document_type_code, document_type_name, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'INCOME_PROOF', 'مدرک درآمد', 'ACTIVE');
INSERT INTO REFERENCE.document_type (id, created_on, created_by, record_version, document_type_code, document_type_name, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'BUSINESS_LICENSE', 'مجوز فعالیت', 'ACTIVE');
INSERT INTO REFERENCE.loan_type (id, created_on, created_by, record_version, loan_type_code, loan_type_name, loan_type_cbi_code, loan_group, obligation_type, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'QARD_HASAN', 'قرض الحسنه', 'QH01', 1, 1, 'ACTIVE');
INSERT INTO REFERENCE.loan_type (id, created_on, created_by, record_version, loan_type_code, loan_type_name, loan_type_cbi_code, loan_group, obligation_type, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'MURABAHA', 'مرابحه', 'MU01', 2, 1, 'ACTIVE');
INSERT INTO REFERENCE.loan_type (id, created_on, created_by, record_version, loan_type_code, loan_type_name, loan_type_cbi_code, loan_group, obligation_type, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'IJARA', 'اجاره به شرط تملیک', 'IJ01', 2, 1, 'ACTIVE');
INSERT INTO REFERENCE.plan_type (id, created_on, created_by, record_version, plan_type_code, plan_type_name, plan_type_cbi_code, min_commission_rate, max_commission_rate, min_penalty_rate, max_penalty_rate, max_penalty_forgiveness_rate, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'QH_STANDARD', 'طرح استاندارد قرض الحسنه', 'PT01', 0, 4, 0, 6, 100, 'ACTIVE');
INSERT INTO REFERENCE.plan_type (id, created_on, created_by, record_version, plan_type_code, plan_type_name, plan_type_cbi_code, min_commission_rate, max_commission_rate, min_penalty_rate, max_penalty_rate, max_penalty_forgiveness_rate, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'RETAIL_GOODS', 'طرح خرید کالا', 'PT02', 0, 6, 0, 8, 50, 'ACTIVE');
INSERT INTO REFERENCE.plan_type (id, created_on, created_by, record_version, plan_type_code, plan_type_name, plan_type_cbi_code, min_commission_rate, max_commission_rate, min_penalty_rate, max_penalty_rate, max_penalty_forgiveness_rate, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'SME_WORKING_CAPITAL', 'سرمایه در گردش کسب و کار', 'PT03', 0, 8, 0, 10, 25, 'ACTIVE');
INSERT INTO REFERENCE.loan_type_plan_type (id, created_on, created_by, record_version, loan_type_id, plan_type_id, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'ACTIVE');
INSERT INTO REFERENCE.loan_type_plan_type (id, created_on, created_by, record_version, loan_type_id, plan_type_id, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2, 2, 'ACTIVE');
INSERT INTO REFERENCE.loan_type_plan_type (id, created_on, created_by, record_version, loan_type_id, plan_type_id, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 2, 3, 'ACTIVE');
INSERT INTO REFERENCE.loan_usage (id, created_on, created_by, record_version, loan_usage_code, loan_usage_name, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'PERSONAL_NEED', 'نیاز شخصی', 'ACTIVE');
INSERT INTO REFERENCE.loan_usage (id, created_on, created_by, record_version, loan_usage_code, loan_usage_name, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'GOODS_PURCHASE', 'خرید کالا', 'ACTIVE');
INSERT INTO REFERENCE.loan_usage (id, created_on, created_by, record_version, loan_usage_code, loan_usage_name, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'WORKING_CAPITAL', 'سرمایه در گردش', 'ACTIVE');
INSERT INTO REFERENCE.economic_section (id, created_on, created_by, record_version, plan_type_id, economic_section_code, economic_section_name, economic_section_cbi_code, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'HOUSEHOLD', 'خانوار / اشخاص', 'ES01', 'ACTIVE');
INSERT INTO REFERENCE.economic_section (id, created_on, created_by, record_version, plan_type_id, economic_section_code, economic_section_name, economic_section_cbi_code, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2, 'SERVICES', 'خدمات', 'ES02', 'ACTIVE');
INSERT INTO REFERENCE.economic_section (id, created_on, created_by, record_version, plan_type_id, economic_section_code, economic_section_name, economic_section_cbi_code, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 3, 'INDUSTRY', 'صنعت', 'ES03', 'ACTIVE');
INSERT INTO REFERENCE.economic_sub_section (id, created_on, created_by, record_version, economic_section_id, economic_sub_section_code, economic_sub_section_name, economic_sub_section_cbi_code, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'PERSONAL_FINANCE', 'مالی شخصی', 'ESS01', 'ACTIVE');
INSERT INTO REFERENCE.economic_sub_section (id, created_on, created_by, record_version, economic_section_id, economic_sub_section_code, economic_sub_section_name, economic_sub_section_cbi_code, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2, 'RETAIL_TRADE', 'خرده فروشی', 'ESS02', 'ACTIVE');
INSERT INTO REFERENCE.economic_sub_section (id, created_on, created_by, record_version, economic_section_id, economic_sub_section_code, economic_sub_section_name, economic_sub_section_cbi_code, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 3, 'MANUFACTURING', 'تولید', 'ESS03', 'ACTIVE');
INSERT INTO REFERENCE.facility_operation_parameter (id, created_on, created_by, record_version, overdue_duration, pastdue_duration, doubtful_duration, transfer_category_method, transfer_principle, transfer_penalty, transfer_commission, parameter_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 10, 30, 90, 1, 1, 1, 1, 'ACTIVE');
INSERT INTO REFERENCE.loan_product_collateral (id, created_on, created_by, record_version, product_collateral_code, product_collateral_name, collateral_category_code, description, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'GUARANTOR', 'ضامن', 'PERSONAL', 'ضامن معتبر با گواهی کسر از حقوق', 'ACTIVE');
INSERT INTO REFERENCE.loan_product_collateral (id, created_on, created_by, record_version, product_collateral_code, product_collateral_name, collateral_category_code, description, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'CASH_DEPOSIT', 'سپرده نقدی', 'CASH', 'مسدودی سپرده نقدی به عنوان وثیقه', 'ACTIVE');
INSERT INTO REFERENCE.loan_product_collateral (id, created_on, created_by, record_version, product_collateral_code, product_collateral_name, collateral_category_code, description, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'PROPERTY', 'ملک', 'REAL_ESTATE', 'وثیقه ملکی با سند رسمی', 'ACTIVE');
INSERT INTO REFERENCE.operation (id, created_on, created_by, record_version, operation_code, operation_name, operation_type_code, facility_step, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'DISBURSEMENT', 'پرداخت / اعطای تسهیلات', 'CREDIT', 1, 'ACTIVE');
INSERT INTO REFERENCE.operation (id, created_on, created_by, record_version, operation_code, operation_name, operation_type_code, facility_step, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'REPAYMENT', 'بازپرداخت', 'DEBIT', 2, 'ACTIVE');
INSERT INTO REFERENCE.operation (id, created_on, created_by, record_version, operation_code, operation_name, operation_type_code, facility_step, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'SETTLEMENT', 'تسویه', 'DEBIT', 3, 'ACTIVE');
INSERT INTO REFERENCE.sub_operation (id, created_on, created_by, record_version, sub_operation_code, sub_operation_name, sub_operation_type, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'PRINCIPAL_PAYMENT', 'پرداخت اصل', 1, 'ACTIVE');
INSERT INTO REFERENCE.sub_operation (id, created_on, created_by, record_version, sub_operation_code, sub_operation_name, sub_operation_type, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 'FEE_COLLECTION', 'وصول کارمزد', 2, 'ACTIVE');
INSERT INTO REFERENCE.sub_operation (id, created_on, created_by, record_version, sub_operation_code, sub_operation_name, sub_operation_type, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 'REVERSAL', 'برگشت عملیات', 3, 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation_loan_type (id, created_on, created_by, record_version, loan_type_id, pattern_operation_version, pattern_name, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'الگوی استاندارد عملیات قرض الحسنه', 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation (id, created_on, created_by, record_version, pattern_operation_loan_type_id, operation_id, operation_order, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 1, 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation (id, created_on, created_by, record_version, pattern_operation_loan_type_id, operation_id, operation_order, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 2, 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation (id, created_on, created_by, record_version, pattern_operation_loan_type_id, operation_id, operation_order, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 3, 3, 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation_detail (id, created_on, created_by, record_version, pattern_operation_id, sub_operation_id, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 2, 1, 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation_detail (id, created_on, created_by, record_version, pattern_operation_id, sub_operation_id, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2, 2, 'ACTIVE');
INSERT INTO REFERENCE.pattern_operation_detail (id, created_on, created_by, record_version, pattern_operation_id, sub_operation_id, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 3, 3, 'ACTIVE');

-- ============================================================
-- 01 - Core: Product / Product Version / Modules
-- ============================================================
INSERT INTO CORE.product (id, created_on, created_by, record_version, institution_id, product_code, product_name, product_class_code, balance_nature_code, product_family_code, default_currency_code, description, product_status_code, is_deleted) VALUES (1001, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'DEP-QH-SAV-001', 'سپرده پس‌انداز قرض‌الحسنه', 'DEPOSIT', 'LIABILITY', 'QARD_HASAN', 'IRR', 'محصول آموزشی سپرده پس‌انداز قرض‌الحسنه', 'APPROVED', FALSE);
INSERT INTO CORE.product (id, created_on, created_by, record_version, institution_id, product_code, product_name, product_class_code, balance_nature_code, product_family_code, default_currency_code, description, product_status_code, is_deleted) VALUES (2001, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'LOAN-QH-001', 'تسهیلات قرض‌الحسنه', 'LOAN', 'ASSET', 'QARD_HASAN', 'IRR', 'محصول آموزشی تسهیلات قرض‌الحسنه', 'APPROVED', FALSE);
INSERT INTO CORE.product_version (id, created_on, created_by, record_version, institution_id, product_id, source_version_id, version_no, valid_from, valid_to, version_status_code, is_current, origination_status_code, servicing_status_code, change_reason, approved_at, approved_by, record_status_code) VALUES (1101, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, NULL, 1, DATE '2026-01-01', NULL, 'APPROVED', TRUE, 'ENABLED', 'ENABLED', 'نسخه اولیه انتشار آموزشی', CURRENT_TIMESTAMP, 'PRODUCT_COMMITTEE', 'ACTIVE');
INSERT INTO CORE.product_version (id, created_on, created_by, record_version, institution_id, product_id, source_version_id, version_no, valid_from, valid_to, version_status_code, is_current, origination_status_code, servicing_status_code, change_reason, approved_at, approved_by, record_status_code) VALUES (2101, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001, NULL, 1, DATE '2026-01-01', NULL, 'APPROVED', TRUE, 'ENABLED', 'ENABLED', 'نسخه اولیه انتشار آموزشی', CURRENT_TIMESTAMP, 'PRODUCT_COMMITTEE', 'ACTIVE');
INSERT INTO CORE.product_version_module (id, created_on, created_by, record_version, institution_id, product_version_id, module_code, is_enabled, configuration_status_code, validation_status_code, config_json) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'DEPOSIT', TRUE, 'CONFIGURED', 'VALIDATED', NULL);
INSERT INTO CORE.product_version_module (id, created_on, created_by, record_version, institution_id, product_version_id, module_code, is_enabled, configuration_status_code, validation_status_code, config_json) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'LOAN', TRUE, 'CONFIGURED', 'VALIDATED', NULL);
INSERT INTO CORE.product_relationship (id, created_on, created_by, record_version, institution_id, source_product_version_id, target_product_id, target_product_version_id, relationship_type_code, priority_no, is_mandatory, min_relation_amount, max_relation_amount, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 1001, 1101, 'REQUIRES', 1, FALSE, NULL, NULL, 'ACTIVE');
INSERT INTO CORE.product_legacy_mapping (id, created_on, created_by, record_version, institution_id, product_id, product_version_id, source_domain_code, source_table_name, source_record_id, source_version_id, migration_batch_id, migrated_at) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001, 1101, 'DEPOSIT', 'LEGACY_SAVINGS_PRODUCT', 'LEG-SAV-001', '1', 'BATCH-2026-01', CURRENT_TIMESTAMP);

-- ============================================================
-- 02 - Common Rules
-- ============================================================
INSERT INTO COMMONRULES.product_eligibility_rule (id, created_on, created_by, record_version, institution_id, product_version_id, party_type_code, customer_segment_code, residency_status_code, nationality_scope_code, gender_code, kyc_level_code, min_age, max_age, aml_risk_max_code, pep_allowed_flag, min_customer_tenure_months, min_account_tenure_months, min_average_balance, priority_no, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'PERSON', 'RETAIL', 'RESIDENT', 'ANY', NULL, 'L1', 18, NULL, 'MEDIUM', TRUE, 0, 0, NULL, 1, 'ACTIVE');
INSERT INTO COMMONRULES.product_eligibility_rule (id, created_on, created_by, record_version, institution_id, product_version_id, party_type_code, customer_segment_code, residency_status_code, nationality_scope_code, gender_code, kyc_level_code, min_age, max_age, aml_risk_max_code, pep_allowed_flag, min_customer_tenure_months, min_account_tenure_months, min_average_balance, priority_no, rule_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'PERSON', 'RETAIL', 'RESIDENT', 'IRANIAN', NULL, 'L2', 22, 65, 'LOW', FALSE, 12, 12, 20000000, 1, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_rule (id, created_on, created_by, record_version, institution_id, product_version_id, channel_code, is_allowed, valid_from, valid_to, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'BRANCH', TRUE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_rule (id, created_on, created_by, record_version, institution_id, product_version_id, channel_code, is_allowed, valid_from, valid_to, rule_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'MOBILE_BANK', TRUE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_rule (id, created_on, created_by, record_version, institution_id, product_version_id, channel_code, is_allowed, valid_from, valid_to, rule_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'BRANCH', TRUE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_operation (id, created_on, created_by, record_version, institution_id, channel_rule_id, operation_code, is_allowed, requires_additional_auth, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'OPEN', TRUE, FALSE, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_operation (id, created_on, created_by, record_version, institution_id, channel_rule_id, operation_code, is_allowed, requires_additional_auth, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'SERVICE', TRUE, FALSE, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_operation (id, created_on, created_by, record_version, institution_id, channel_rule_id, operation_code, is_allowed, requires_additional_auth, record_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 'SERVICE', TRUE, TRUE, 'ACTIVE');
INSERT INTO COMMONRULES.product_channel_operation (id, created_on, created_by, record_version, institution_id, channel_rule_id, operation_code, is_allowed, requires_additional_auth, record_status_code) VALUES (4, CURRENT_TIMESTAMP, 'SEED', 1, 1, 3, 'APPLY', TRUE, FALSE, 'ACTIVE');
INSERT INTO COMMONRULES.product_org_scope (id, created_on, created_by, record_version, institution_id, product_version_id, org_unit_type_code, org_unit_id, org_unit_code, is_allowed, valid_from, valid_to, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'ALL_BRANCHES', NULL, 'ALL', TRUE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_org_scope (id, created_on, created_by, record_version, institution_id, product_version_id, org_unit_type_code, org_unit_id, org_unit_code, is_allowed, valid_from, valid_to, rule_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'ALL_BRANCHES', NULL, 'ALL', TRUE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_required_document (id, created_on, created_by, record_version, institution_id, product_version_id, document_type_id, requirement_stage_code, process_step_no, copy_count, is_mandatory, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 1, 'OPENING', 1, 1, TRUE, 'ACTIVE');
INSERT INTO COMMONRULES.product_required_document (id, created_on, created_by, record_version, institution_id, product_version_id, document_type_id, requirement_stage_code, process_step_no, copy_count, is_mandatory, rule_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 1, 'APPLICATION', 1, 1, TRUE, 'ACTIVE');
INSERT INTO COMMONRULES.product_required_document (id, created_on, created_by, record_version, institution_id, product_version_id, document_type_id, requirement_stage_code, process_step_no, copy_count, is_mandatory, rule_status_code) VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 2, 'APPLICATION', 2, 1, TRUE, 'ACTIVE');
INSERT INTO COMMONRULES.product_required_inquiry (id, created_on, created_by, record_version, institution_id, product_version_id, inquiry_type_code, requirement_stage_code, max_result_age_minutes, is_mandatory, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'CREDIT_BUREAU', 'APPLICATION', 1440, TRUE, 'ACTIVE');
INSERT INTO COMMONRULES.product_required_inquiry (id, created_on, created_by, record_version, institution_id, product_version_id, inquiry_type_code, requirement_stage_code, max_result_age_minutes, is_mandatory, rule_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'BOUNCED_CHEQUE_CHECK', 'APPLICATION', 1440, TRUE, 'ACTIVE');
INSERT INTO COMMONRULES.product_pricing_rule (id, created_on, created_by, record_version, institution_id, product_version_id, pricing_purpose_code, pricing_method_code, currency_code, base_rate, is_tiered_rate, valid_from, valid_to, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'DEPOSIT_BONUS', 'FIXED', 'IRR', 0, FALSE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_pricing_rule (id, created_on, created_by, record_version, institution_id, product_version_id, pricing_purpose_code, pricing_method_code, currency_code, base_rate, is_tiered_rate, valid_from, valid_to, rule_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'LOAN_FEE', 'FIXED', 'IRR', 0, FALSE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO COMMONRULES.product_pricing_component (id, created_on, created_by, record_version, institution_id, pricing_rule_id, component_type_code, calculation_method_code, rate_value, min_rate, max_rate, fixed_amount, min_amount, max_amount, percentage_base_code, is_waivable, display_order, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'CARD_ISSUANCE_FEE', 'FIXED_AMOUNT', NULL, NULL, NULL, 500000, NULL, NULL, NULL, TRUE, 1, 'ACTIVE');
INSERT INTO COMMONRULES.product_pricing_component (id, created_on, created_by, record_version, institution_id, pricing_rule_id, component_type_code, calculation_method_code, rate_value, min_rate, max_rate, fixed_amount, min_amount, max_amount, percentage_base_code, is_waivable, display_order, record_status_code) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 'FILE_OPENING_FEE', 'FIXED_AMOUNT', NULL, NULL, NULL, 1000000, NULL, NULL, NULL, FALSE, 1, 'ACTIVE');
INSERT INTO COMMONRULES.product_rate_tier (id, created_on, created_by, record_version, institution_id, pricing_component_id, tier_no, min_amount, max_amount, min_term_value, max_term_value, term_unit_code, rate_value, valid_from, valid_to) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 1, 0, NULL, NULL, NULL, NULL, 0, DATE '2026-01-01', NULL);

-- ============================================================
-- 03 - Deposit Module (QH Savings, product_version_id=1101)
-- ============================================================
INSERT INTO DEPOSIT.deposit_product_profile (id, created_on, created_by, record_version, institution_id, product_version_id, deposit_group_code, deposit_type_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'QH_SAVINGS_GROUP', 'QH_SAVINGS');
INSERT INTO DEPOSIT.deposit_product_opening_rule (id, created_on, created_by, record_version, institution_id, product_version_id, min_opening_amount, max_opening_amount, min_required_balance, max_allowed_balance, max_customer_account_count, max_bank_account_count, is_introducer_required) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 100000, NULL, 0, NULL, 5, NULL, FALSE);
INSERT INTO DEPOSIT.deposit_product_transaction_rule (id, created_on, created_by, record_version, institution_id, product_version_id, transaction_type_code, is_allowed, min_transaction_amount, max_transaction_amount, daily_amount_limit, daily_count_limit, monthly_amount_limit, monthly_count_limit) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'DEPOSIT', TRUE, 10000, NULL, NULL, NULL, NULL, NULL);
INSERT INTO DEPOSIT.deposit_product_transaction_rule (id, created_on, created_by, record_version, institution_id, product_version_id, transaction_type_code, is_allowed, min_transaction_amount, max_transaction_amount, daily_amount_limit, daily_count_limit, monthly_amount_limit, monthly_count_limit) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'WITHDRAWAL', TRUE, 10000, 500000000, 500000000, 10, NULL, NULL);
INSERT INTO DEPOSIT.deposit_product_withdrawal_media (id, created_on, created_by, record_version, institution_id, product_version_id, withdrawal_media_code, channel_code, is_allowed, max_transaction_amount, daily_amount_limit, daily_count_limit) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'DEBIT_CARD', 'ALL', TRUE, 200000000, 200000000, 10);
INSERT INTO DEPOSIT.deposit_product_withdrawal_media (id, created_on, created_by, record_version, institution_id, product_version_id, withdrawal_media_code, channel_code, is_allowed, max_transaction_amount, daily_amount_limit, daily_count_limit) VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'BRANCH_INSTRUCTION', 'BRANCH', TRUE, NULL, NULL, NULL);
INSERT INTO DEPOSIT.deposit_product_joint_rule (id, created_on, created_by, record_version, institution_id, product_version_id, ownership_type_code, min_joint_owner_count, max_joint_owner_count, signing_rule_code, min_required_signer_count) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'JOINT_AND', 1, 4, 'ANY_ONE', 1);
INSERT INTO DEPOSIT.deposit_product_hold_rule (id, created_on, created_by, record_version, institution_id, product_version_id, hold_type_code, is_supported, min_hold_amount, max_hold_amount) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'FULL', TRUE, NULL, NULL);
INSERT INTO DEPOSIT.deposit_product_dormancy_rule (id, created_on, created_by, record_version, institution_id, product_version_id, inactivity_period_value, inactivity_period_unit_code, warning_period_value, warning_period_unit_code, reactivation_method_code, auto_reactivation_allowed, valid_from, valid_to) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 12, 'MONTH', 1, 'MONTH', 'BRANCH_VISIT', FALSE, DATE '2026-01-01', NULL);
INSERT INTO DEPOSIT.deposit_product_closure_rule (id, created_on, created_by, record_version, institution_id, product_version_id, closure_type_code, is_closure_allowed, is_partial_closure_allowed, balance_destination_code, effective_from_date, effective_to_date, status_code, description) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1101, 'CUSTOMER_REQUEST', TRUE, FALSE, 'CASH_OR_TRANSFER', DATE '2026-01-01', NULL, 'ACTIVE', 'بستن حساب با درخواست مشتری - نمونه آموزشی');
INSERT INTO DEPOSIT.deposit_product_closure_precheck (id, created_on, created_by, record_version, institution_id, closure_rule_id, check_type_code, is_mandatory, failure_action_code, sequence_no, description) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'NO_OPEN_HOLD', TRUE, 'BLOCK', 1, 'بررسی نبود مسدودی باز روی حساب');
INSERT INTO DEPOSIT.deposit_product_closure_settlement_rule (id, created_on, created_by, record_version, institution_id, closure_rule_id, settlement_component_code, settlement_method_code, destination_code, is_mandatory, sequence_no, description) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'REMAINING_BALANCE', 'CASH_OR_TRANSFER', 'CUSTOMER_DEFAULT_ACCOUNT', TRUE, 1, 'تسویه مانده باقیمانده حساب');
INSERT INTO DEPOSIT.deposit_product_closure_approval_rule (id, created_on, created_by, record_version, institution_id, closure_rule_id, approval_level_code, is_mandatory, approval_sequence_no, min_amount, max_amount, description) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'BRANCH_MANAGER', FALSE, 1, NULL, NULL, 'تأیید مدیر شعبه برای مبالغ بالا - اختیاری');

-- ============================================================
-- 04 - Loan Module (QH Loan, product_version_id=2101)
-- ============================================================
INSERT INTO LOAN.loan_product_profile (id, created_on, created_by, record_version, institution_id, product_version_id, loan_type_id, plan_type_id, loan_usage_id, economic_sub_section_id, operation_parameter_id, party_nature_code, currency_type_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 1, 1, 1, 1, 1, 'PERSON', 'IRR');
INSERT INTO LOAN.loan_eligibility_extension (id, created_on, created_by, record_version, institution_id, eligibility_rule_id, min_income_amount, min_credit_score, max_risk_grade_code, required_guarantor_count, employment_type_code, cbi_tracking_required, credit_inquiry_required, aml_check_required) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 50000000, 600, 'B', 2, 'SALARIED', TRUE, TRUE, TRUE);
INSERT INTO LOAN.loan_financial_extension (id, created_on, created_by, record_version, institution_id, product_version_id, min_facility_amount, max_facility_amount, valid_from, valid_to, rule_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 50000000, 300000000, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO LOAN.loan_product_repayment_rule (id, created_on, created_by, record_version, institution_id, product_version_id, repayment_rule_code, repayment_rule_name, repayment_method_code, installment_frequency_code, min_term_duration, max_term_duration, term_unit_code, min_installment_count, max_installment_count, installment_interval, installment_interval_unit_code, grace_allowed, min_grace_duration, max_grace_duration, grace_unit_code, grace_method_code, prepayment_allowed, partial_prepayment_allowed, early_settlement_allowed, valid_from, valid_to, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 'STANDARD_INSTALLMENT', 'بازپرداخت اقساطی استاندارد قرض‌الحسنه', 'EQUAL_INSTALLMENT', 'MONTHLY', 6, 60, 'MONTH', 6, 60, 1, 'MONTH', TRUE, 1, 3, 'MONTH', 'DEFERRED', TRUE, TRUE, TRUE, DATE '2026-01-01', NULL, 'ACTIVE');
INSERT INTO LOAN.loan_product_process_rule (id, created_on, created_by, record_version, institution_id, product_version_id, application_validity_days, approval_validity_days, contract_validity_days, manual_approval_required, committee_approval_required, multi_level_approval_required, cbi_tracking_required, external_inquiry_required, allow_override, override_approval_level_code, valid_from, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 30, 15, 15, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, NULL, DATE '2026-01-01', 'ACTIVE');
INSERT INTO LOAN.loan_product_collateral_rule (id, created_on, created_by, record_version, institution_id, product_version_id, loan_product_collateral_id, is_required, min_coverage_percent, max_coverage_percent, substitution_allowed, third_party_allowed, currency_match_required, priority_no, record_status_code) VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2101, 1, TRUE, 100.0, NULL, FALSE, TRUE, TRUE, 1, 'ACTIVE');

-- Advance identity sequences past the explicit seed IDs
ALTER TABLE CORE.product ALTER COLUMN id RESTART WITH 3001;
ALTER TABLE CORE.product_version ALTER COLUMN id RESTART WITH 3101;
