-- ============================================================
-- Party module seed data (schema PARTY)
-- Educational/demo data only - not real customer information.
-- Institution/tenant 1 = the single demo bank used throughout this project.
-- Rewritten to match the "Party and Customer Integrated Domains" EA model:
-- every classification code is now a real FK into a REF_* reference table
-- instead of an embedded Java enum, so those catalogs must be seeded first.
-- ============================================================

-- ---------- Reference/lookup catalogs (REF_*, uniform CODE/TITLE_FA/DESCRIPTION_FA/DISPLAY_ORDER/IS_ACTIVE shape) ----------
INSERT INTO PARTY.GEOGRAPHIC_LOCATION (LOCATION_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION_FA)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 'تهران، ایران', 0, 'Y', 'محل تولد نمونه برای سناریوهای آموزشی');
INSERT INTO PARTY.REF_ADDRESS_TYPE (ADDRESS_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('RESIDENTIAL', CURRENT_TIMESTAMP, 'SEED', 1, 'سکونتی', 0, 'Y');
INSERT INTO PARTY.REF_ADDRESS_TYPE (ADDRESS_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('REGISTERED', CURRENT_TIMESTAMP, 'SEED', 1, 'نشانی ثبتی', 10, 'Y');
INSERT INTO PARTY.REF_ADDRESS_TYPE (ADDRESS_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MAILING', CURRENT_TIMESTAMP, 'SEED', 1, 'مکاتباتی', 20, 'Y');

INSERT INTO PARTY.REF_AUDIT_ACTION (ACTION_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('CREATE', CURRENT_TIMESTAMP, 'SEED', 1, 'ایجاد', 0, 'Y');
INSERT INTO PARTY.REF_AUDIT_ACTION (ACTION_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('UPDATE', CURRENT_TIMESTAMP, 'SEED', 1, 'ویرایش', 10, 'Y');
INSERT INTO PARTY.REF_AUDIT_ACTION (ACTION_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DELETE', CURRENT_TIMESTAMP, 'SEED', 1, 'حذف', 20, 'Y');

INSERT INTO PARTY.REF_AUDIT_SCOPE (AUDIT_SCOPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('CORE', CURRENT_TIMESTAMP, 'SEED', 1, 'هسته مرکزی', 0, 'Y');
INSERT INTO PARTY.REF_AUDIT_SCOPE (AUDIT_SCOPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('TENANT', CURRENT_TIMESTAMP, 'SEED', 1, 'اطلاعات صندوق', 10, 'Y');

INSERT INTO PARTY.REF_AUDIT_VALUE_TYPE (VALUE_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('STRING', CURRENT_TIMESTAMP, 'SEED', 1, 'متنی', 0, 'Y');
INSERT INTO PARTY.REF_AUDIT_VALUE_TYPE (VALUE_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('NUMBER', CURRENT_TIMESTAMP, 'SEED', 1, 'عددی', 10, 'Y');
INSERT INTO PARTY.REF_AUDIT_VALUE_TYPE (VALUE_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DATE', CURRENT_TIMESTAMP, 'SEED', 1, 'تاریخ', 20, 'Y');

INSERT INTO PARTY.REF_AUTHORITY_BASIS (AUTHORITY_BASIS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('POWER_OF_ATTORNEY', CURRENT_TIMESTAMP, 'SEED', 1, 'وکالت‌نامه', 0, 'Y');

INSERT INTO PARTY.REF_CHANNEL (CHANNEL_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('BRANCH_COUNTER', CURRENT_TIMESTAMP, 'SEED', 1, 'باجه شعبه', 0, 'Y');
INSERT INTO PARTY.REF_CHANNEL (CHANNEL_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MOBILE_APP', CURRENT_TIMESTAMP, 'SEED', 1, 'اپلیکیشن موبایل', 10, 'Y');

INSERT INTO PARTY.REF_CONTACT_ADDRESS_ASSOC_TYPE (ASSOCIATION_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('RESIDES_AT', CURRENT_TIMESTAMP, 'SEED', 1, 'محل سکونت', 0, 'Y');

INSERT INTO PARTY.REF_CONTACT_PURPOSE (CONTACT_PURPOSE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('PERSONAL', CURRENT_TIMESTAMP, 'SEED', 1, 'شخصی', 0, 'Y');
INSERT INTO PARTY.REF_CONTACT_PURPOSE (CONTACT_PURPOSE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('BUSINESS', CURRENT_TIMESTAMP, 'SEED', 1, 'کسب‌وکار', 10, 'Y');

INSERT INTO PARTY.REF_CONTACT_TYPE (CONTACT_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MOBILE_PHONE', CURRENT_TIMESTAMP, 'SEED', 1, 'تلفن همراه', 0, 'Y');
INSERT INTO PARTY.REF_CONTACT_TYPE (CONTACT_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('LANDLINE_PHONE', CURRENT_TIMESTAMP, 'SEED', 1, 'تلفن ثابت', 10, 'Y');
INSERT INTO PARTY.REF_CONTACT_TYPE (CONTACT_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('EMAIL', CURRENT_TIMESTAMP, 'SEED', 1, 'ایمیل', 20, 'Y');

INSERT INTO PARTY.REF_CONTEXT_TYPE (CONTEXT_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ACCOUNT', CURRENT_TIMESTAMP, 'SEED', 1, 'حساب', 0, 'Y');
INSERT INTO PARTY.REF_CONTEXT_TYPE (CONTEXT_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('CONTRACT', CURRENT_TIMESTAMP, 'SEED', 1, 'قرارداد', 10, 'Y');

INSERT INTO PARTY.REF_COUNTRY (COUNTRY_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('IRN', CURRENT_TIMESTAMP, 'SEED', 1, 'ایران', 0, 'Y');
INSERT INTO PARTY.REF_COUNTRY (COUNTRY_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ARE', CURRENT_TIMESTAMP, 'SEED', 1, 'امارات متحده عربی', 10, 'Y');

INSERT INTO PARTY.REF_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ACTIVE', CURRENT_TIMESTAMP, 'SEED', 1, 'فعال', 0, 'Y');
INSERT INTO PARTY.REF_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DORMANT', CURRENT_TIMESTAMP, 'SEED', 1, 'راکد', 10, 'Y');

INSERT INTO PARTY.REF_DATA_SOURCE (DATA_SOURCE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('BRANCH_ENTRY', CURRENT_TIMESTAMP, 'SEED', 1, 'ثبت در شعبه', 0, 'Y');
INSERT INTO PARTY.REF_DATA_SOURCE (DATA_SOURCE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DIGITAL_ONBOARDING', CURRENT_TIMESTAMP, 'SEED', 1, 'ثبت‌نام دیجیتال', 10, 'Y');
INSERT INTO PARTY.REF_DATA_SOURCE (DATA_SOURCE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DATA_MIGRATION', CURRENT_TIMESTAMP, 'SEED', 1, 'مهاجرت داده', 20, 'Y');

INSERT INTO PARTY.REF_ENTERPRISE_SIZE (ENTERPRISE_SIZE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MICRO', CURRENT_TIMESTAMP, 'SEED', 1, 'خرد', 0, 'Y');
INSERT INTO PARTY.REF_ENTERPRISE_SIZE (ENTERPRISE_SIZE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('SMALL', CURRENT_TIMESTAMP, 'SEED', 1, 'کوچک', 10, 'Y');

INSERT INTO PARTY.REF_GENDER (GENDER_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MALE', CURRENT_TIMESTAMP, 'SEED', 1, 'مرد', 0, 'Y');
INSERT INTO PARTY.REF_GENDER (GENDER_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('FEMALE', CURRENT_TIMESTAMP, 'SEED', 1, 'زن', 10, 'Y');

INSERT INTO PARTY.REF_GROUP_MEMBER_ROLE (MEMBER_ROLE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('OWNER', CURRENT_TIMESTAMP, 'SEED', 1, 'مالک', 0, 'Y');

INSERT INTO PARTY.REF_GROUP_TYPE (GROUP_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('OWNERSHIP', CURRENT_TIMESTAMP, 'SEED', 1, 'ساختار مالکیت', 0, 'Y');
INSERT INTO PARTY.REF_GROUP_TYPE (GROUP_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('FAMILY', CURRENT_TIMESTAMP, 'SEED', 1, 'خانواده', 10, 'Y');

INSERT INTO PARTY.REF_IDENTIFIER_TYPE (IDENTIFIER_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('NATIONAL_ID', CURRENT_TIMESTAMP, 'SEED', 1, 'کد ملی', 0, 'Y');
INSERT INTO PARTY.REF_IDENTIFIER_TYPE (IDENTIFIER_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('REGISTRATION_NUMBER', CURRENT_TIMESTAMP, 'SEED', 1, 'شماره ثبت', 10, 'Y');
INSERT INTO PARTY.REF_IDENTIFIER_TYPE (IDENTIFIER_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('PASSPORT', CURRENT_TIMESTAMP, 'SEED', 1, 'گذرنامه', 20, 'Y');

INSERT INTO PARTY.REF_KYC_STATUS (KYC_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('NOT_STARTED', CURRENT_TIMESTAMP, 'SEED', 1, 'شروع‌نشده', 0, 'Y');
INSERT INTO PARTY.REF_KYC_STATUS (KYC_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('VERIFIED', CURRENT_TIMESTAMP, 'SEED', 1, 'احراز شده', 10, 'Y');

INSERT INTO PARTY.REF_MARITAL_STATUS (MARITAL_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('SINGLE', CURRENT_TIMESTAMP, 'SEED', 1, 'مجرد', 0, 'Y');
INSERT INTO PARTY.REF_MARITAL_STATUS (MARITAL_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MARRIED', CURRENT_TIMESTAMP, 'SEED', 1, 'متأهل', 10, 'Y');
INSERT INTO PARTY.REF_MARITAL_STATUS (MARITAL_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DIVORCED', CURRENT_TIMESTAMP, 'SEED', 1, 'مطلقه', 20, 'Y');
INSERT INTO PARTY.REF_MARITAL_STATUS (MARITAL_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('WIDOWED', CURRENT_TIMESTAMP, 'SEED', 1, 'بیوه', 30, 'Y');

INSERT INTO PARTY.REF_OFFICER_ROLE (OFFICER_ROLE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('MANAGING_DIRECTOR', CURRENT_TIMESTAMP, 'SEED', 1, 'مدیرعامل', 0, 'Y');

INSERT INTO PARTY.REF_ORG_ACTIVITY_STATUS (ACTIVITY_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ACTIVE', CURRENT_TIMESTAMP, 'SEED', 1, 'فعال', 0, 'Y');
INSERT INTO PARTY.REF_ORG_ACTIVITY_STATUS (ACTIVITY_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DISSOLVED', CURRENT_TIMESTAMP, 'SEED', 1, 'منحل‌شده', 10, 'Y');

INSERT INTO PARTY.REF_OWNERSHIP_TYPE (OWNERSHIP_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('PRIVATE', CURRENT_TIMESTAMP, 'SEED', 1, 'خصوصی', 0, 'Y');
INSERT INTO PARTY.REF_OWNERSHIP_TYPE (OWNERSHIP_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('COOPERATIVE', CURRENT_TIMESTAMP, 'SEED', 1, 'تعاونی', 10, 'Y');

INSERT INTO PARTY.REF_PARTY_TYPE (PARTY_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('PERSON', CURRENT_TIMESTAMP, 'SEED', 1, 'شخص حقیقی', 0, 'Y');
INSERT INTO PARTY.REF_PARTY_TYPE (PARTY_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ORGANIZATION', CURRENT_TIMESTAMP, 'SEED', 1, 'شخص حقوقی', 10, 'Y');

INSERT INTO PARTY.REF_RELATIONSHIP_TYPE (RELATIONSHIP_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('REPRESENTS', CURRENT_TIMESTAMP, 'SEED', 1, 'نمایندگی', 0, 'Y');

INSERT INTO PARTY.REF_RESIDENCE_STATUS (RESIDENCE_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('RESIDENT', CURRENT_TIMESTAMP, 'SEED', 1, 'مقیم', 0, 'Y');
INSERT INTO PARTY.REF_RESIDENCE_STATUS (RESIDENCE_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('NON_RESIDENT', CURRENT_TIMESTAMP, 'SEED', 1, 'غیرمقیم', 10, 'Y');

INSERT INTO PARTY.REF_ROLE_TYPE (ROLE_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('CUSTOMER', CURRENT_TIMESTAMP, 'SEED', 1, 'مشتری', 0, 'Y');
INSERT INTO PARTY.REF_ROLE_TYPE (ROLE_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('LEGAL_REPRESENTATIVE', CURRENT_TIMESTAMP, 'SEED', 1, 'نماینده قانونی', 10, 'Y');

INSERT INTO PARTY.REF_SIGNING_RULE (SIGNING_RULE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('SINGLE', CURRENT_TIMESTAMP, 'SEED', 1, 'امضای یک‌نفره', 0, 'Y');

INSERT INTO PARTY.REF_SPECIMEN_TYPE (SPECIMEN_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('WET_SIGNATURE', CURRENT_TIMESTAMP, 'SEED', 1, 'امضای دستی', 0, 'Y');

INSERT INTO PARTY.REF_VERIFICATION_METHOD (VERIFICATION_METHOD_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('IN_PERSON', CURRENT_TIMESTAMP, 'SEED', 1, 'حضوری', 0, 'Y');
INSERT INTO PARTY.REF_VERIFICATION_METHOD (VERIFICATION_METHOD_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('DOCUMENT_REVIEW', CURRENT_TIMESTAMP, 'SEED', 1, 'بررسی مدارک', 10, 'Y');

INSERT INTO PARTY.REF_VERIFICATION_STATUS (VERIFICATION_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('PENDING', CURRENT_TIMESTAMP, 'SEED', 1, 'در انتظار بررسی', 0, 'Y');
INSERT INTO PARTY.REF_VERIFICATION_STATUS (VERIFICATION_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('VERIFIED', CURRENT_TIMESTAMP, 'SEED', 1, 'احراز شده', 10, 'Y');
INSERT INTO PARTY.REF_VERIFICATION_STATUS (VERIFICATION_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('UNVERIFIED', CURRENT_TIMESTAMP, 'SEED', 1, 'احراز نشده', 20, 'Y');
INSERT INTO PARTY.REF_VERIFICATION_STATUS (VERIFICATION_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('REJECTED', CURRENT_TIMESTAMP, 'SEED', 1, 'رد شده', 30, 'Y');
INSERT INTO PARTY.REF_VERIFICATION_STATUS (VERIFICATION_STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('EXPIRED', CURRENT_TIMESTAMP, 'SEED', 1, 'منقضی شده', 40, 'Y');

INSERT INTO PARTY.REF_WORKFLOW_STATUS (STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ACTIVE', CURRENT_TIMESTAMP, 'SEED', 1, 'فعال', 0, 'Y');
INSERT INTO PARTY.REF_WORKFLOW_STATUS (STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('SUSPENDED', CURRENT_TIMESTAMP, 'SEED', 1, 'معلق', 10, 'Y');
INSERT INTO PARTY.REF_WORKFLOW_STATUS (STATUS_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('TERMINATED', CURRENT_TIMESTAMP, 'SEED', 1, 'خاتمه‌یافته', 20, 'Y');

INSERT INTO PARTY.REF_PROVINCE (PROVINCE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, COUNTRY_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('THR', CURRENT_TIMESTAMP, 'SEED', 1, 'استان تهران', 'IRN', 0, 'Y');
INSERT INTO PARTY.REF_PROVINCE (PROVINCE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, COUNTRY_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ESF', CURRENT_TIMESTAMP, 'SEED', 1, 'استان اصفهان', 'IRN', 10, 'Y');

INSERT INTO PARTY.REF_COUNTY (COUNTY_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, PROVINCE_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('THR-CT', CURRENT_TIMESTAMP, 'SEED', 1, 'شهرستان تهران', 'THR', 0, 'Y');

INSERT INTO PARTY.REF_CITY (CITY_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, PROVINCE_CODE, COUNTY_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('TEHRAN', CURRENT_TIMESTAMP, 'SEED', 1, 'تهران', 'THR', 'THR-CT', 0, 'Y');
INSERT INTO PARTY.REF_CITY (CITY_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, PROVINCE_CODE, COUNTY_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('ESFAHAN', CURRENT_TIMESTAMP, 'SEED', 1, 'اصفهان', 'ESF', NULL, 10, 'Y');

INSERT INTO PARTY.REF_DISTRICT (DISTRICT_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, CITY_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('THR-D3', CURRENT_TIMESTAMP, 'SEED', 1, 'منطقه ۳ تهران', 'TEHRAN', 0, 'Y');

INSERT INTO PARTY.REF_AUDIT_ENTITY_TYPE (ENTITY_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DEFAULT_SCOPE_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('PARTY', CURRENT_TIMESTAMP, 'SEED', 1, 'پارتی', 'CORE', 0, 'Y');
INSERT INTO PARTY.REF_AUDIT_ENTITY_TYPE (ENTITY_TYPE_CODE, CREATED_ON, CREATED_BY, RECORD_VERSION, TITLE_FA, DEFAULT_SCOPE_CODE, DISPLAY_ORDER, IS_ACTIVE)
VALUES ('CUSTOMER', CURRENT_TIMESTAMP, 'SEED', 1, 'مشتری', 'TENANT', 10, 'Y');

-- ---------- PARTY (lean central identity root) ----------
INSERT INTO PARTY.PARTY (PARTY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_TYPE_CODE, VERIFICATION_STATUS_CODE, CREATION_SOURCE_CODE, IS_CURRENT)
VALUES (1001, CURRENT_TIMESTAMP, 'SEED', 1, 'PERSON', 'VERIFIED', 'BRANCH_ENTRY', 'Y');
INSERT INTO PARTY.PARTY (PARTY_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_TYPE_CODE, VERIFICATION_STATUS_CODE, CREATION_SOURCE_CODE, IS_CURRENT)
VALUES (2001, CURRENT_TIMESTAMP, 'SEED', 1, 'ORGANIZATION', 'VERIFIED', 'BRANCH_ENTRY', 'Y');

-- ---------- PERSON (shares PARTY_ID as its own PK) ----------
INSERT INTO PARTY.PERSON (PARTY_ID, BIRTH_DATE, GENDER_CODE, BIRTH_COUNTRY_CODE, BIRTH_PLACE_ID,
    FATHER_GIVEN_NAME, MARITAL_STATUS_CODE, RESIDENCE_STATUS_CODE, PHYSICAL_ABILITY)
VALUES (1001, DATE '1990-05-15', 'MALE', 'IRN', 1, 'علی', 'MARRIED', 'RESIDENT', 'NONE');

-- ---------- ORGANIZATION (own surrogate ORGANIZATION_ID, 1:1 FK to PARTY_ID) ----------
INSERT INTO PARTY.ORGANIZATION (ORGANIZATION_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_ID, REGISTERED_NAME, REGISTRATION_NO, REGISTRATION_COUNTRY_CODE,
    INCORPORATION_DATE, LISTED_COMPANY_FLAG, ACTIVITY_STATUS_CODE, MAIN_ACTIVITY_DESCRIPTION,
    EMPLOYEE_COUNT, ENTERPRISE_SIZE_CODE, OWNERSHIP_TYPE_CODE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1,
    2001, 'شرکت تعاونی نمونه قرض‌الحسنه', '12345', 'IRN',
    DATE '2015-01-01', 'N', 'ACTIVE', 'خدمات مالی و قرض‌الحسنه',
    25, 'SMALL', 'PRIVATE');

-- ---------- PARTY_MEMBERSHIP (the tenant-scoping boundary) ----------
INSERT INTO PARTY.PARTY_MEMBERSHIP (PARTY_MEMBERSHIP_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1001);
INSERT INTO PARTY.PARTY_MEMBERSHIP (PARTY_MEMBERSHIP_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_ID)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2001);

-- ---------- PARTY_NAME ----------
INSERT INTO PARTY.PARTY_NAME (PARTY_NAME_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_ID, GIVEN_NAME, FAMILY_NAME, FULL_NAME, IS_PRIMARY, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1001, 'محمد', 'رضایی', 'محمد رضایی', 'Y', DATE '2020-01-01');
INSERT INTO PARTY.PARTY_NAME (PARTY_NAME_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_ID, FULL_NAME, IS_PRIMARY, VALID_FROM)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2001, 'شرکت تعاونی نمونه قرض‌الحسنه', 'Y', DATE '2015-01-01');

-- ---------- PARTY_IDENTIFIER ----------
INSERT INTO PARTY.PARTY_IDENTIFIER (PARTY_IDENTIFIER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_ID, IDENTIFIER_TYPE_CODE, IDENTIFIER_VALUE,
    ISSUE_DATE, IS_PRIMARY, IS_ACTIVE, VERIFICATION_STATUS_CODE, VERIFICATION_METHOD_CODE,
    VALID_FROM, IDENTIFIER_MATCH_KEY)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1001, 'NATIONAL_ID', '0012345678',
    DATE '2008-06-01', 'Y', 'Y', 'VERIFIED', 'IN_PERSON', DATE '2008-06-01', 'NATIONAL_ID:0012345678');
INSERT INTO PARTY.PARTY_IDENTIFIER (PARTY_IDENTIFIER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    PARTY_ID, IDENTIFIER_TYPE_CODE, IDENTIFIER_VALUE,
    IS_PRIMARY, IS_ACTIVE, VERIFICATION_STATUS_CODE, VERIFICATION_METHOD_CODE,
    VALID_FROM, IDENTIFIER_MATCH_KEY)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 2001, 'REGISTRATION_NUMBER', '12345',
    'Y', 'Y', 'VERIFIED', 'DOCUMENT_REVIEW', DATE '2015-01-01', 'REGISTRATION_NUMBER:12345');

-- ---------- ADDRESS (shared master data, plain FK-resolved location codes) ----------
INSERT INTO PARTY.ADDRESS (ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    COUNTRY_CODE, PROVINCE_CODE, CITY_CODE, MAIN_STREET_TEXT, PLAQUE_NO, UNIT_NO, POSTAL_CODE, ADDRESS_LINE1)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'IRN', 'THR', 'TEHRAN', 'خیابان ولیعصر', '125', '4', '1234567890',
    'تهران، خیابان ولیعصر، پلاک ۱۲۵، واحد ۴');
INSERT INTO PARTY.ADDRESS (ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    COUNTRY_CODE, PROVINCE_CODE, CITY_CODE, MAIN_STREET_TEXT, PLAQUE_NO, POSTAL_CODE, ADDRESS_LINE1)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'IRN', 'THR', 'TEHRAN', 'بلوار میرداماد', '48', '1987654321',
    'تهران، بلوار میرداماد، پلاک ۴۸ (دفتر مرکزی شرکت)');

-- ---------- PARTY_ADDRESS ----------
INSERT INTO PARTY.PARTY_ADDRESS (PARTY_ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, ADDRESS_ID, ADDRESS_TYPE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 1, 'RESIDENTIAL', 'Y', DATE '2020-01-01');
INSERT INTO PARTY.PARTY_ADDRESS (PARTY_ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, ADDRESS_ID, ADDRESS_TYPE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 2, 'REGISTERED', 'Y', DATE '2015-01-01');

-- ---------- CONTACT_POINT ----------
INSERT INTO PARTY.CONTACT_POINT (CONTACT_POINT_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, CONTACT_TYPE_CODE, CONTACT_VALUE, PURPOSE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'MOBILE_PHONE', '+989121234567', 'PERSONAL', 'Y', DATE '2020-01-01');
INSERT INTO PARTY.CONTACT_POINT (CONTACT_POINT_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, CONTACT_TYPE_CODE, CONTACT_VALUE, PURPOSE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'EMAIL', 'mohammad.rezaei@example.com', 'PERSONAL', 'N', DATE '2020-01-01');
INSERT INTO PARTY.CONTACT_POINT (CONTACT_POINT_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, CONTACT_TYPE_CODE, CONTACT_VALUE, AREA_CODE, PURPOSE_CODE, IS_PRIMARY, VALID_FROM)
VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 'LANDLINE_PHONE', '88889999', '021', 'BUSINESS', 'Y', DATE '2015-01-01');

-- ---------- CONTACT_POINT_ADDRESS (org landline is located at the registered office) ----------
INSERT INTO PARTY.CONTACT_POINT_ADDRESS (CONTACT_POINT_ADDRESS_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    INSTITUTION_ID, PARTY_MEMBERSHIP_ID, CONTACT_POINT_ID, PARTY_ADDRESS_ID, ASSOCIATION_TYPE_CODE,
    IS_PRIMARY_FOR_ADDRESS, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 3, 2, 'RESIDES_AT', 'Y', DATE '2015-01-01');

-- ---------- PARTY_ROLE (generic role/context extensibility point) ----------
INSERT INTO PARTY.PARTY_ROLE (PARTY_ROLE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, ROLE_TYPE_CODE, CONTEXT_TYPE_CODE, CONTEXT_ID, VALID_FROM, STATUS_CODE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'CUSTOMER', 'ACCOUNT', 'ACC-0001001', DATE '2020-01-01', 'ACTIVE');
INSERT INTO PARTY.PARTY_ROLE (PARTY_ROLE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, ROLE_TYPE_CODE, CONTEXT_TYPE_CODE, CONTEXT_ID, PRINCIPAL_MEMBERSHIP_ID,
    RELATIONSHIP_TYPE_CODE, AUTHORITY_BASIS_CODE, AUTHORITY_DOCUMENT_NO, VALID_FROM, STATUS_CODE)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'LEGAL_REPRESENTATIVE', 'CONTRACT', 'CTR-0000500', 2,
    'REPRESENTS', 'POWER_OF_ATTORNEY', 'POA-2026-001', DATE '2020-01-01', 'ACTIVE');
INSERT INTO PARTY.PARTY_ROLE (PARTY_ROLE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, ROLE_TYPE_CODE, CONTEXT_TYPE_CODE, CONTEXT_ID, VALID_FROM, STATUS_CODE)
VALUES (3, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 'CUSTOMER', 'ACCOUNT', 'ACC-0002001', DATE '2015-01-01', 'ACTIVE');

-- ---------- PARTY_GROUP + PARTY_GROUP_MEMBER (ownership / UBO tracking) ----------
INSERT INTO PARTY.PARTY_GROUP (GROUP_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    GROUP_TYPE_CODE, GROUP_NAME, STATUS_CODE, EFFECTIVE_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 'OWNERSHIP', 'ساختار مالکیت شرکت تعاونی نمونه', 'ACTIVE',
    DATE '2015-01-01');
INSERT INTO PARTY.PARTY_GROUP_MEMBER (GROUP_MEMBER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    GROUP_ID, PARTY_MEMBERSHIP_ID, MEMBER_ROLE_CODE, OWNERSHIP_PERCENT, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 1, 'OWNER', 100.000, DATE '2015-01-01');

-- ---------- CUSTOMER (own surrogate CUSTOMER_ID, FK to PARTY_MEMBERSHIP) ----------
INSERT INTO PARTY.CUSTOMER (CUSTOMER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, CUSTOMER_NO, CUSTOMER_STATUS_CODE, ONBOARDING_DATE, KYC_STATUS_CODE, HOME_BRANCH_CODE)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 'CUST-0001001', 'ACTIVE', DATE '2020-01-01', 'VERIFIED', 'BR-001');
INSERT INTO PARTY.CUSTOMER (CUSTOMER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, CUSTOMER_NO, CUSTOMER_STATUS_CODE, ONBOARDING_DATE, KYC_STATUS_CODE, HOME_BRANCH_CODE)
VALUES (2, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 'CUST-0002001', 'ACTIVE', DATE '2015-01-01', 'VERIFIED', 'BR-001');

-- ---------- ORGANIZATION_OFFICER (person acting as an officer of the organization, both sides via PARTY_MEMBERSHIP) ----------
INSERT INTO PARTY.ORGANIZATION_OFFICER (ORGANIZATION_OFFICER_ID, CREATED_ON, CREATED_BY, RECORD_VERSION,
    INSTITUTION_ID, ORGANIZATION_MEMBERSHIP_ID, OFFICER_MEMBERSHIP_ID, OFFICER_ROLE_CODE, VALID_FROM)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 2, 1, 'MANAGING_DIRECTOR', DATE '2015-01-01');

-- ---------- SIGNATURE_SPECIMEN ----------
INSERT INTO PARTY.SIGNATURE_SPECIMEN (SIGNATURE_ID, CREATED_ON, CREATED_BY, RECORD_VERSION, INSTITUTION_ID,
    PARTY_MEMBERSHIP_ID, SIGNATORY_MEMBERSHIP_ID, SPECIMEN_TYPE_CODE, SIGNATURE_IMAGE, EFFECTIVE_FROM,
    STATUS_CODE, SIGNING_RULE_CODE, VERIFICATION_STATUS_CODE, CAPTURE_CHANNEL_CODE, CAPTURED_BY)
VALUES (1, CURRENT_TIMESTAMP, 'SEED', 1, 1, 1, 1, 'WET_SIGNATURE', X'00', DATE '2020-01-01',
    'ACTIVE', 'SINGLE', 'VERIFIED', 'BRANCH_COUNTER', 'SEED');

-- ---------- AUDIT_EVENT + AUDIT_FIELD_CHANGE (illustrative rows - no automatic capture is wired up) ----------
INSERT INTO PARTY.AUDIT_EVENT (AUDIT_EVENT_ID, AUDIT_SCOPE_CODE, ENTITY_TYPE_CODE, ENTITY_ID,
    PARTY_ID, PARTY_MEMBERSHIP_ID, TENANT_ID, ACTION_CODE, EVENT_AT, EVENT_BY, SOURCE_CHANNEL_CODE,
    CORRELATION_ID)
VALUES (1, 'CORE', 'PARTY', 1001, 1001, 1, 1, 'CREATE', CURRENT_TIMESTAMP, 'SEED', 'BRANCH_COUNTER',
    'CORR-2026-0002');
INSERT INTO PARTY.AUDIT_FIELD_CHANGE (AUDIT_FIELD_CHANGE_ID, AUDIT_EVENT_ID, FIELD_NAME, VALUE_TYPE_CODE,
    NEW_VALUE, IS_SENSITIVE, IS_REDACTED)
VALUES (1, 1, 'VERIFICATION_STATUS_CODE', 'STRING', 'VERIFIED', 'N', 'N');

-- ============================================================
-- Advance every sequence past the explicit seed IDs used above,
-- so subsequent inserts through the REST API never collide.
-- ============================================================
ALTER SEQUENCE PARTY.GEOGRAPHIC_LOCATION_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_ID_SEQ RESTART WITH 3001;
ALTER SEQUENCE PARTY.ORGANIZATION_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_MEMBERSHIP_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_NAME_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_IDENTIFIER_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.ADDRESS_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_ADDRESS_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.CONTACT_POINT_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.CONTACT_POINT_ADDRESS_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_ROLE_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_GROUP_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.PARTY_GROUP_MEMBER_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.CUSTOMER_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.ORGANIZATION_OFFICER_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.SIGNATURE_SPECIMEN_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.AUDIT_EVENT_ID_SEQ RESTART WITH 100;
ALTER SEQUENCE PARTY.AUDIT_FIELD_CHANGE_ID_SEQ RESTART WITH 100;
